# Generated by Django 2.1.1 on 2018-12-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('submitter', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=3, max_digits=8)),
                ('submission_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CharityStakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='charityproject',
            name='stakeholder',
            field=models.ManyToManyField(blank=True, to='projects.CharityStakeholder'),
        ),
    ]
